In [ ]:
import os
import pandas as pd
from datetime import datetime
import shutil
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Segregation data to train test and valid

In [ ]:
# Path to the folder containing the image files
folder_path = "D:\\FOG\\Visibility_dataset_rename_1-17423"

# Get the list of all files in the folder
file_list = os.listdir(folder_path)

# Filter the list to only include image files (JPEG)
image_list = [f for f in file_list if f.endswith('.jpg')]

# Destination folder for the images  change accoedingly
destination_folder = "D:\\FOG\\new_dataset\\validation"
# Read the excel file
df = pd.read_csv('C:\\Users\\HP\Downloads\\Bins_Dataset\\validation_data.csv')


def create_folder_if_not_exists(folder_path):
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        print(f"Folder '{folder_path}' created successfully.")
    else:
        print(f"Folder '{folder_path}' already exists.")

# Create folders for binary and multiclass
create_folder_if_not_exists(os.path.join(destination_folder, "binary", "fog"))
create_folder_if_not_exists(os.path.join(destination_folder, "binary", "No_fog"))

for multi in range(1, 6):
    create_folder_if_not_exists(os.path.join(destination_folder, "multiclass", str(multi)))


for index, row in df.iterrows():
    dt = row['datetime']
    date_time = datetime.strptime(dt, '%Y-%m-%d %H:%M:%S')

    year_1 = date_time.year
    month_1 = date_time.month
    day_1 = date_time.day
    hour_1 = date_time.hour
    minute_1 = date_time.minute
    new_vis = row['vis']

    binary = row['status']
    multi = row['category']

    for all_images in image_list:
        file_parts = all_images.split("-")
        year = int(file_parts[0][1:])
        month = int(file_parts[1])
        day = int(file_parts[2][0:2])
        time_hr = int(file_parts[2][2:4])
        time_min = int(file_parts[2][5:7])

        if (year, month, day, time_hr, time_min) == (year_1, month_1, day_1, hour_1, minute_1):
            source_path = os.path.join(folder_path, all_images)

            if binary == 1:
                destination_path = os.path.join(destination_folder, "binary", "fog", all_images)
            else:
                destination_path = os.path.join(destination_folder, "binary", "No_fog", all_images)
            try:
                shutil.copy(source_path, destination_path)
                print(f"Image '{all_images}' copied successfully.")
            except shutil.Error as e:
                print(f"Error copying image: {e}")

            destination_path = os.path.join(destination_folder, "multiclass", str(multi), all_images)
            try:
                shutil.copy(source_path, destination_path)
                print(f"Image '{all_images}' copied successfully.")
            except shutil.Error as e:
                print(f"Error copying image: {e}")

Folder 'D:\FOG\new_dataset\validation\binary\fog' created successfully.
Folder 'D:\FOG\new_dataset\validation\binary\No_fog' created successfully.
Folder 'D:\FOG\new_dataset\validation\multiclass\1' created successfully.
Folder 'D:\FOG\new_dataset\validation\multiclass\2' created successfully.
Folder 'D:\FOG\new_dataset\validation\multiclass\3' created successfully.
Folder 'D:\FOG\new_dataset\validation\multiclass\4' created successfully.
Folder 'D:\FOG\new_dataset\validation\multiclass\5' created successfully.
Image 'R2022-12-1913_26_10_1.70633.jpg' copied successfully.
Image 'R2022-12-1913_26_10_1.70633.jpg' copied successfully.
Image 'R2022-12-1913_36_13_1.687.jpg' copied successfully.
Image 'R2022-12-1913_36_13_1.687.jpg' copied successfully.
Image 'R2022-12-1913_46_16_1.71367.jpg' copied successfully.
Image 'R2022-12-1913_46_16_1.71367.jpg' copied successfully.
Image 'R2022-12-1913_56_19_1.77367.jpg' copied successfully.
Image 'R2022-12-1913_56_19_1.77367.jpg' copied successfully.

Image 'R2022-12-2000_29_18_0.309.jpg' copied successfully.
Image 'R2022-12-2000_29_18_0.309.jpg' copied successfully.
Image 'R2022-12-2000_39_21_0.374.jpg' copied successfully.
Image 'R2022-12-2000_39_21_0.374.jpg' copied successfully.
Image 'R2022-12-2000_49_24_0.317333.jpg' copied successfully.
Image 'R2022-12-2000_49_24_0.317333.jpg' copied successfully.
Image 'R2022-12-2000_59_27_0.313448.jpg' copied successfully.
Image 'R2022-12-2000_59_27_0.313448.jpg' copied successfully.
Image 'R2022-12-2001_09_29_0.309.jpg' copied successfully.
Image 'R2022-12-2001_09_29_0.309.jpg' copied successfully.
Image 'R2022-12-2001_19_32_0.218.jpg' copied successfully.
Image 'R2022-12-2001_19_32_0.218.jpg' copied successfully.
Image 'R2022-12-2001_29_35_0.187667.jpg' copied successfully.
Image 'R2022-12-2001_29_35_0.187667.jpg' copied successfully.
Image 'R2022-12-2001_39_38_0.0876667.jpg' copied successfully.
Image 'R2022-12-2001_39_38_0.0876667.jpg' copied successfully.
Image 'R2022-12-2001_49_41_0.0

Image 'R2022-12-2519_10_52_2.0.jpg' copied successfully.
Image 'R2022-12-2519_10_52_2.0.jpg' copied successfully.
Image 'R2022-12-2519_20_55_2.0.jpg' copied successfully.
Image 'R2022-12-2519_20_55_2.0.jpg' copied successfully.
Image 'R2022-12-2519_30_58_2.0.jpg' copied successfully.
Image 'R2022-12-2519_30_58_2.0.jpg' copied successfully.
Image 'R2022-12-2519_41_00_2.0.jpg' copied successfully.
Image 'R2022-12-2519_41_00_2.0.jpg' copied successfully.
Image 'R2022-12-2519_51_03_2.0.jpg' copied successfully.
Image 'R2022-12-2519_51_03_2.0.jpg' copied successfully.
Image 'R2022-12-2520_01_06_2.0.jpg' copied successfully.
Image 'R2022-12-2520_01_06_2.0.jpg' copied successfully.
Image 'R2022-12-2520_11_09_2.0.jpg' copied successfully.
Image 'R2022-12-2520_11_09_2.0.jpg' copied successfully.
Image 'R2022-12-2520_21_12_2.0.jpg' copied successfully.
Image 'R2022-12-2520_21_12_2.0.jpg' copied successfully.
Image 'R2022-12-2520_31_15_2.0.jpg' copied successfully.
Image 'R2022-12-2520_31_15_2.0.

Image 'R2022-12-2606_44_07_0.0412903.jpg' copied successfully.
Image 'R2022-12-2606_44_07_0.0412903.jpg' copied successfully.
Image 'R2022-12-2606_54_10_0.0406667.jpg' copied successfully.
Image 'R2022-12-2606_54_10_0.0406667.jpg' copied successfully.
Image 'R2022-12-2607_04_13_0.04.jpg' copied successfully.
Image 'R2022-12-2607_04_13_0.04.jpg' copied successfully.
Image 'R2022-12-2607_14_16_0.034.jpg' copied successfully.
Image 'R2022-12-2607_14_16_0.034.jpg' copied successfully.
Image 'R2022-12-2607_24_18_0.0406667.jpg' copied successfully.
Image 'R2022-12-2607_24_18_0.0406667.jpg' copied successfully.
Image 'R2022-12-2607_34_21_0.044.jpg' copied successfully.
Image 'R2022-12-2607_34_21_0.044.jpg' copied successfully.
Image 'R2022-12-2607_44_24_0.046.jpg' copied successfully.
Image 'R2022-12-2607_44_24_0.046.jpg' copied successfully.
Image 'R2022-12-2607_54_27_0.0443333.jpg' copied successfully.
Image 'R2022-12-2607_54_27_0.0443333.jpg' copied successfully.
Image 'R2022-12-2608_04_30

Image 'R2022-12-2618_27_26_0.864.jpg' copied successfully.
Image 'R2022-12-2618_27_26_0.864.jpg' copied successfully.
Image 'R2022-12-2618_37_28_0.762333.jpg' copied successfully.
Image 'R2022-12-2618_37_28_0.762333.jpg' copied successfully.
Image 'R2022-12-2618_47_31_0.750345.jpg' copied successfully.
Image 'R2022-12-2618_47_31_0.750345.jpg' copied successfully.
Image 'R2022-12-2618_57_34_0.685667.jpg' copied successfully.
Image 'R2022-12-2618_57_34_0.685667.jpg' copied successfully.
Image 'R2022-12-2619_07_37_0.617667.jpg' copied successfully.
Image 'R2022-12-2619_07_37_0.617667.jpg' copied successfully.
Image 'R2022-12-2619_17_40_0.645517.jpg' copied successfully.
Image 'R2022-12-2619_17_40_0.645517.jpg' copied successfully.
Image 'R2022-12-2619_27_43_0.609333.jpg' copied successfully.
Image 'R2022-12-2619_27_43_0.609333.jpg' copied successfully.
Image 'R2022-12-2619_37_46_0.564333.jpg' copied successfully.
Image 'R2022-12-2619_37_46_0.564333.jpg' copied successfully.
Image 'R2022-1

Image 'R2022-12-2706_30_49_0.294.jpg' copied successfully.
Image 'R2022-12-2706_30_49_0.294.jpg' copied successfully.
Image 'R2022-12-2706_40_52_0.173448.jpg' copied successfully.
Image 'R2022-12-2706_40_52_0.173448.jpg' copied successfully.
Image 'R2022-12-2706_50_55_0.169333.jpg' copied successfully.
Image 'R2022-12-2706_50_55_0.169333.jpg' copied successfully.
Image 'R2022-12-2707_00_58_0.237.jpg' copied successfully.
Image 'R2022-12-2707_00_58_0.237.jpg' copied successfully.
Image 'R2022-12-2707_11_01_0.293103.jpg' copied successfully.
Image 'R2022-12-2707_11_01_0.293103.jpg' copied successfully.
Image 'R2022-12-2707_21_04_0.284333.jpg' copied successfully.
Image 'R2022-12-2707_21_04_0.284333.jpg' copied successfully.
Image 'R2022-12-2707_31_06_0.499333.jpg' copied successfully.
Image 'R2022-12-2707_31_06_0.499333.jpg' copied successfully.
Image 'R2022-12-2707_41_09_0.712414.jpg' copied successfully.
Image 'R2022-12-2707_41_09_0.712414.jpg' copied successfully.
Image 'R2022-12-2707

Image 'R2022-12-2814_17_29_2.0.jpg' copied successfully.
Image 'R2022-12-2814_17_29_2.0.jpg' copied successfully.
Image 'R2022-12-2814_27_32_2.0.jpg' copied successfully.
Image 'R2022-12-2814_27_32_2.0.jpg' copied successfully.
Image 'R2022-12-2814_37_35_2.0.jpg' copied successfully.
Image 'R2022-12-2814_37_35_2.0.jpg' copied successfully.
Image 'R2022-12-2814_47_38_2.0.jpg' copied successfully.
Image 'R2022-12-2814_47_38_2.0.jpg' copied successfully.
Image 'R2022-12-2814_57_42_2.0.jpg' copied successfully.
Image 'R2022-12-2814_57_42_2.0.jpg' copied successfully.
Image 'R2022-12-2815_07_45_2.0.jpg' copied successfully.
Image 'R2022-12-2815_07_45_2.0.jpg' copied successfully.
Image 'R2022-12-2815_17_47_2.0.jpg' copied successfully.
Image 'R2022-12-2815_17_47_2.0.jpg' copied successfully.
Image 'R2022-12-2815_27_50_2.0.jpg' copied successfully.
Image 'R2022-12-2815_27_50_2.0.jpg' copied successfully.
Image 'R2022-12-2815_37_53_2.0.jpg' copied successfully.
Image 'R2022-12-2815_37_53_2.0.

Image 'R2022-12-3013_35_36_2.0.jpg' copied successfully.
Image 'R2022-12-3013_35_36_2.0.jpg' copied successfully.
Image 'R2022-12-3013_36_39_2.0.jpg' copied successfully.
Image 'R2022-12-3013_36_39_2.0.jpg' copied successfully.
Image 'R2022-12-3013_37_42_2.0.jpg' copied successfully.
Image 'R2022-12-3013_37_42_2.0.jpg' copied successfully.
Image 'R2022-12-3013_38_45_2.0.jpg' copied successfully.
Image 'R2022-12-3013_38_45_2.0.jpg' copied successfully.
Image 'R2022-12-3013_39_47_2.0.jpg' copied successfully.
Image 'R2022-12-3013_39_47_2.0.jpg' copied successfully.
Image 'R2022-12-3013_40_50_2.0.jpg' copied successfully.
Image 'R2022-12-3013_40_50_2.0.jpg' copied successfully.
Image 'R2022-12-3013_41_53_2.0.jpg' copied successfully.
Image 'R2022-12-3013_41_53_2.0.jpg' copied successfully.
Image 'R2022-12-3013_42_56_2.0.jpg' copied successfully.
Image 'R2022-12-3013_42_56_2.0.jpg' copied successfully.
Image 'R2022-12-3013_43_59_2.0.jpg' copied successfully.
Image 'R2022-12-3013_43_59_2.0.

Image 'R2022-12-3014_52_01_2.0.jpg' copied successfully.
Image 'R2022-12-3014_52_01_2.0.jpg' copied successfully.
Image 'R2022-12-3014_53_04_2.0.jpg' copied successfully.
Image 'R2022-12-3014_53_04_2.0.jpg' copied successfully.
Image 'R2022-12-3014_54_07_2.0.jpg' copied successfully.
Image 'R2022-12-3014_54_07_2.0.jpg' copied successfully.
Image 'R2022-12-3014_55_10_2.0.jpg' copied successfully.
Image 'R2022-12-3014_55_10_2.0.jpg' copied successfully.
Image 'R2022-12-3014_56_12_2.0.jpg' copied successfully.
Image 'R2022-12-3014_56_12_2.0.jpg' copied successfully.
Image 'R2022-12-3014_57_15_2.0.jpg' copied successfully.
Image 'R2022-12-3014_57_15_2.0.jpg' copied successfully.
Image 'R2022-12-3014_58_18_2.0.jpg' copied successfully.
Image 'R2022-12-3014_58_18_2.0.jpg' copied successfully.
Image 'R2022-12-3014_59_21_2.0.jpg' copied successfully.
Image 'R2022-12-3014_59_21_2.0.jpg' copied successfully.
Image 'R2022-12-3015_00_24_2.0.jpg' copied successfully.
Image 'R2022-12-3015_00_24_2.0.

Image 'R2022-12-3018_47_56_1.17967.jpg' copied successfully.
Image 'R2022-12-3018_47_56_1.17967.jpg' copied successfully.
Image 'R2022-12-3018_48_59_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_48_59_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_50_02_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_50_02_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_51_05_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_51_05_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_52_07_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_52_07_1.22897.jpg' copied successfully.
Image 'R2022-12-3018_53_10_1.22267.jpg' copied successfully.
Image 'R2022-12-3018_53_10_1.22267.jpg' copied successfully.
Image 'R2022-12-3018_54_13_1.22267.jpg' copied successfully.
Image 'R2022-12-3018_54_13_1.22267.jpg' copied successfully.
Image 'R2022-12-3018_59_34_1.22267.jpg' copied successfully.
Image 'R2022-12-3018_59_34_1.22267.jpg' copied successfully.
Image 'R2022-12-3019_02_

Image 'R2022-12-3112_55_54_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_55_03_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_55_03_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_55_54_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_55_54_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_06_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_06_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_57_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_57_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_06_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_06_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_57_0.928667.jpg' copied successfully.
Image 'R2022-12-3112_58_57_0.928667.jpg' copied successfully.
Image 'R2022-12-3113_01_09_0.968667.jpg' copied successfully.
Image 'R2022-12-3113_01_09_0.968667.jpg' copied successfully.
Image 'R2022-12-3113_02_00_0.968667.jpg' copied successfully.
Image 'R

Image 'R2023-01-0114_17_10_1.622.jpg' copied successfully.
Image 'R2023-01-0114_17_10_1.622.jpg' copied successfully.
Image 'R2023-01-0114_22_13_1.67333.jpg' copied successfully.
Image 'R2023-01-0114_22_13_1.67333.jpg' copied successfully.
Image 'R2023-01-0114_27_15_1.75467.jpg' copied successfully.
Image 'R2023-01-0114_27_15_1.75467.jpg' copied successfully.
Image 'R2023-01-0114_32_18_1.70517.jpg' copied successfully.
Image 'R2023-01-0114_32_18_1.70517.jpg' copied successfully.
Image 'R2023-01-0114_37_21_1.68133.jpg' copied successfully.
Image 'R2023-01-0114_37_21_1.68133.jpg' copied successfully.
Image 'R2023-01-0114_42_24_1.685.jpg' copied successfully.
Image 'R2023-01-0114_42_24_1.685.jpg' copied successfully.
Image 'R2023-01-0114_47_27_1.737.jpg' copied successfully.
Image 'R2023-01-0114_47_27_1.737.jpg' copied successfully.
Image 'R2023-01-0114_52_29_1.831.jpg' copied successfully.
Image 'R2023-01-0114_52_29_1.831.jpg' copied successfully.
Image 'R2023-01-0114_57_32_1.79667.jpg' 

Image 'R2023-01-0120_54_20_1.39433.jpg' copied successfully.
Image 'R2023-01-0120_54_20_1.39433.jpg' copied successfully.
Image 'R2023-01-0120_59_23_1.39433.jpg' copied successfully.
Image 'R2023-01-0120_59_23_1.39433.jpg' copied successfully.
Image 'R2023-01-0121_04_26_1.399.jpg' copied successfully.
Image 'R2023-01-0121_04_26_1.399.jpg' copied successfully.
Image 'R2023-01-0121_09_28_1.402.jpg' copied successfully.
Image 'R2023-01-0121_09_28_1.402.jpg' copied successfully.
Image 'R2023-01-0121_14_31_1.34759.jpg' copied successfully.
Image 'R2023-01-0121_14_31_1.34759.jpg' copied successfully.
Image 'R2023-01-0121_19_34_1.33933.jpg' copied successfully.
Image 'R2023-01-0121_19_34_1.33933.jpg' copied successfully.
Image 'R2023-01-0121_24_37_1.335.jpg' copied successfully.
Image 'R2023-01-0121_24_37_1.335.jpg' copied successfully.
Image 'R2023-01-0121_29_40_1.312.jpg' copied successfully.
Image 'R2023-01-0121_29_40_1.312.jpg' copied successfully.
Image 'R2023-01-0121_34_42_1.31233.jpg' 

Image 'R2023-01-0211_01_30_1.82667.jpg' copied successfully.
Image 'R2023-01-0211_01_30_1.82667.jpg' copied successfully.
Image 'R2023-01-0211_06_33_1.93517.jpg' copied successfully.
Image 'R2023-01-0211_06_33_1.93517.jpg' copied successfully.
Image 'R2023-01-0211_11_36_1.92367.jpg' copied successfully.
Image 'R2023-01-0211_11_36_1.92367.jpg' copied successfully.
Image 'R2023-01-0211_16_38_1.94733.jpg' copied successfully.
Image 'R2023-01-0211_16_38_1.94733.jpg' copied successfully.
Image 'R2023-01-0211_21_41_1.99767.jpg' copied successfully.
Image 'R2023-01-0211_21_41_1.99767.jpg' copied successfully.
Image 'R2023-01-0211_26_44_1.98567.jpg' copied successfully.
Image 'R2023-01-0211_26_44_1.98567.jpg' copied successfully.
Image 'R2023-01-0211_31_47_1.999.jpg' copied successfully.
Image 'R2023-01-0211_31_47_1.999.jpg' copied successfully.
Image 'R2023-01-0211_36_50_1.99828.jpg' copied successfully.
Image 'R2023-01-0211_36_50_1.99828.jpg' copied successfully.
Image 'R2023-01-0211_41_53_2

Image 'R2023-01-0217_30_10_1.471.jpg' copied successfully.
Image 'R2023-01-0217_30_10_1.471.jpg' copied successfully.
Image 'R2023-01-0217_35_12_1.37833.jpg' copied successfully.
Image 'R2023-01-0217_35_12_1.37833.jpg' copied successfully.
Image 'R2023-01-0217_45_18_1.38633.jpg' copied successfully.
Image 'R2023-01-0217_45_18_1.38633.jpg' copied successfully.
Image 'R2023-01-0217_50_21_1.28833.jpg' copied successfully.
Image 'R2023-01-0217_50_21_1.28833.jpg' copied successfully.
Image 'R2023-01-0217_55_24_1.19621.jpg' copied successfully.
Image 'R2023-01-0217_55_24_1.19621.jpg' copied successfully.
Image 'R2023-01-0218_00_27_1.173.jpg' copied successfully.
Image 'R2023-01-0218_00_27_1.173.jpg' copied successfully.
Image 'R2023-01-0218_05_29_1.18.jpg' copied successfully.
Image 'R2023-01-0218_05_29_1.18.jpg' copied successfully.
Image 'R2023-01-0218_10_32_1.19267.jpg' copied successfully.
Image 'R2023-01-0218_10_32_1.19267.jpg' copied successfully.
Image 'R2023-01-0218_15_35_1.139.jpg' 

Image 'R2023-01-0309_57_42_0.224333.jpg' copied successfully.
Image 'R2023-01-0309_57_42_0.224333.jpg' copied successfully.
Image 'R2023-01-0310_02_44_0.299667.jpg' copied successfully.
Image 'R2023-01-0310_02_44_0.299667.jpg' copied successfully.
Image 'R2023-01-0310_07_47_0.416333.jpg' copied successfully.
Image 'R2023-01-0310_07_47_0.416333.jpg' copied successfully.
Image 'R2023-01-0310_12_50_0.593333.jpg' copied successfully.
Image 'R2023-01-0310_12_50_0.593333.jpg' copied successfully.
Image 'R2023-01-0310_17_53_0.742759.jpg' copied successfully.
Image 'R2023-01-0310_17_53_0.742759.jpg' copied successfully.
Image 'R2023-01-0310_22_56_0.847.jpg' copied successfully.
Image 'R2023-01-0310_22_56_0.847.jpg' copied successfully.
Image 'R2023-01-0310_27_59_0.766.jpg' copied successfully.
Image 'R2023-01-0310_27_59_0.766.jpg' copied successfully.
Image 'R2023-01-0310_33_02_0.760667.jpg' copied successfully.
Image 'R2023-01-0310_33_02_0.760667.jpg' copied successfully.
Image 'R2023-01-0310

Image 'R2023-01-0317_58_24_1.411.jpg' copied successfully.
Image 'R2023-01-0317_58_24_1.411.jpg' copied successfully.
Image 'R2023-01-0318_03_26_1.36.jpg' copied successfully.
Image 'R2023-01-0318_03_26_1.36.jpg' copied successfully.
Image 'R2023-01-0318_08_29_1.371.jpg' copied successfully.
Image 'R2023-01-0318_08_29_1.371.jpg' copied successfully.
Image 'R2023-01-0318_13_32_1.39526.jpg' copied successfully.
Image 'R2023-01-0318_13_32_1.39526.jpg' copied successfully.
Image 'R2023-01-0318_18_35_1.386.jpg' copied successfully.
Image 'R2023-01-0318_18_35_1.386.jpg' copied successfully.
Image 'R2023-01-0318_23_38_1.346.jpg' copied successfully.
Image 'R2023-01-0318_23_38_1.346.jpg' copied successfully.
Image 'R2023-01-0318_28_41_1.38.jpg' copied successfully.
Image 'R2023-01-0318_28_41_1.38.jpg' copied successfully.
Image 'R2023-01-0318_33_43_1.444.jpg' copied successfully.
Image 'R2023-01-0318_33_43_1.444.jpg' copied successfully.
Image 'R2023-01-0318_38_46_1.49367.jpg' copied successfu

Image 'R2023-01-0400_01_49_0.797333.jpg' copied successfully.
Image 'R2023-01-0400_01_49_0.797333.jpg' copied successfully.
Image 'R2023-01-0400_06_52_0.839667.jpg' copied successfully.
Image 'R2023-01-0400_06_52_0.839667.jpg' copied successfully.
Image 'R2023-01-0400_11_55_0.896.jpg' copied successfully.
Image 'R2023-01-0400_11_55_0.896.jpg' copied successfully.
Image 'R2023-01-0400_16_58_0.844333.jpg' copied successfully.
Image 'R2023-01-0400_16_58_0.844333.jpg' copied successfully.
Image 'R2023-01-0400_22_01_0.878333.jpg' copied successfully.
Image 'R2023-01-0400_22_01_0.878333.jpg' copied successfully.
Image 'R2023-01-0400_27_03_0.844828.jpg' copied successfully.
Image 'R2023-01-0400_27_03_0.844828.jpg' copied successfully.
Image 'R2023-01-0400_32_06_0.86.jpg' copied successfully.
Image 'R2023-01-0400_32_06_0.86.jpg' copied successfully.
Image 'R2023-01-0400_37_09_0.870667.jpg' copied successfully.
Image 'R2023-01-0400_37_09_0.870667.jpg' copied successfully.
Image 'R2023-01-0400_4

Image 'R2023-01-0406_00_11_1.76167.jpg' copied successfully.
Image 'R2023-01-0406_00_11_1.76167.jpg' copied successfully.
Image 'R2023-01-0406_05_14_1.824.jpg' copied successfully.
Image 'R2023-01-0406_05_14_1.824.jpg' copied successfully.
Image 'R2023-01-0406_10_16_1.804.jpg' copied successfully.
Image 'R2023-01-0406_10_16_1.804.jpg' copied successfully.
Image 'R2023-01-0406_15_19_1.716.jpg' copied successfully.
Image 'R2023-01-0406_15_19_1.716.jpg' copied successfully.
Image 'R2023-01-0406_20_22_1.68724.jpg' copied successfully.
Image 'R2023-01-0406_20_22_1.68724.jpg' copied successfully.
Image 'R2023-01-0406_25_25_1.63633.jpg' copied successfully.
Image 'R2023-01-0406_25_25_1.63633.jpg' copied successfully.
Image 'R2023-01-0406_30_28_1.67533.jpg' copied successfully.
Image 'R2023-01-0406_30_28_1.67533.jpg' copied successfully.
Image 'R2023-01-0406_35_31_1.61333.jpg' copied successfully.
Image 'R2023-01-0406_35_31_1.61333.jpg' copied successfully.
Image 'R2023-01-0406_40_34_1.67667.j

Image 'R2023-01-0411_58_34_2.0.jpg' copied successfully.
Image 'R2023-01-0411_58_34_2.0.jpg' copied successfully.
Image 'R2023-01-0412_03_36_2.0.jpg' copied successfully.
Image 'R2023-01-0412_03_36_2.0.jpg' copied successfully.
Image 'R2023-01-0412_08_39_2.0.jpg' copied successfully.
Image 'R2023-01-0412_08_39_2.0.jpg' copied successfully.
Image 'R2023-01-0412_13_42_2.0.jpg' copied successfully.
Image 'R2023-01-0412_13_42_2.0.jpg' copied successfully.
Image 'R2023-01-0412_18_45_2.0.jpg' copied successfully.
Image 'R2023-01-0412_18_45_2.0.jpg' copied successfully.
Image 'R2023-01-0412_23_48_2.0.jpg' copied successfully.
Image 'R2023-01-0412_23_48_2.0.jpg' copied successfully.
Image 'R2023-01-0412_28_51_2.0.jpg' copied successfully.
Image 'R2023-01-0412_28_51_2.0.jpg' copied successfully.
Image 'R2023-01-0412_33_54_2.0.jpg' copied successfully.
Image 'R2023-01-0412_33_54_2.0.jpg' copied successfully.
Image 'R2023-01-0412_38_57_2.0.jpg' copied successfully.
Image 'R2023-01-0412_38_57_2.0.

Image 'R2023-01-0418_27_15_1.01833.jpg' copied successfully.
Image 'R2023-01-0418_27_15_1.01833.jpg' copied successfully.
Image 'R2023-01-0418_32_17_1.0.jpg' copied successfully.
Image 'R2023-01-0418_32_17_1.0.jpg' copied successfully.
Image 'R2023-01-0418_37_20_0.913.jpg' copied successfully.
Image 'R2023-01-0418_37_20_0.913.jpg' copied successfully.
Image 'R2023-01-0418_42_23_0.953333.jpg' copied successfully.
Image 'R2023-01-0418_42_23_0.953333.jpg' copied successfully.
Image 'R2023-01-0418_47_26_0.917333.jpg' copied successfully.
Image 'R2023-01-0418_47_26_0.917333.jpg' copied successfully.
Image 'R2023-01-0418_52_29_0.874667.jpg' copied successfully.
Image 'R2023-01-0418_52_29_0.874667.jpg' copied successfully.
Image 'R2023-01-0418_57_32_0.823793.jpg' copied successfully.
Image 'R2023-01-0418_57_32_0.823793.jpg' copied successfully.
Image 'R2023-01-0419_02_35_0.96.jpg' copied successfully.
Image 'R2023-01-0419_02_35_0.96.jpg' copied successfully.
Image 'R2023-01-0419_07_37_0.88566

Image 'R2023-01-0500_15_31_0.659667.jpg' copied successfully.
Image 'R2023-01-0500_15_31_0.659667.jpg' copied successfully.
Image 'R2023-01-0500_20_34_0.728667.jpg' copied successfully.
Image 'R2023-01-0500_20_34_0.728667.jpg' copied successfully.
Image 'R2023-01-0500_25_36_0.736333.jpg' copied successfully.
Image 'R2023-01-0500_25_36_0.736333.jpg' copied successfully.
Image 'R2023-01-0500_30_39_0.739.jpg' copied successfully.
Image 'R2023-01-0500_30_39_0.739.jpg' copied successfully.
Image 'R2023-01-0500_35_42_0.707586.jpg' copied successfully.
Image 'R2023-01-0500_35_42_0.707586.jpg' copied successfully.
Image 'R2023-01-0500_40_45_0.706.jpg' copied successfully.
Image 'R2023-01-0500_40_45_0.706.jpg' copied successfully.
Image 'R2023-01-0500_45_48_0.761333.jpg' copied successfully.
Image 'R2023-01-0500_45_48_0.761333.jpg' copied successfully.
Image 'R2023-01-0500_50_51_0.842667.jpg' copied successfully.
Image 'R2023-01-0500_50_51_0.842667.jpg' copied successfully.
Image 'R2023-01-0500

Image 'R2023-01-0506_13_51_0.936667.jpg' copied successfully.
Image 'R2023-01-0506_13_51_0.936667.jpg' copied successfully.
Image 'R2023-01-0506_18_54_0.927667.jpg' copied successfully.
Image 'R2023-01-0506_18_54_0.927667.jpg' copied successfully.
Image 'R2023-01-0506_23_57_1.17633.jpg' copied successfully.
Image 'R2023-01-0506_23_57_1.17633.jpg' copied successfully.
Image 'R2023-01-0506_28_59_1.43069.jpg' copied successfully.
Image 'R2023-01-0506_28_59_1.43069.jpg' copied successfully.
Image 'R2023-01-0506_34_02_1.024.jpg' copied successfully.
Image 'R2023-01-0506_34_02_1.024.jpg' copied successfully.
Image 'R2023-01-0506_39_05_1.25233.jpg' copied successfully.
Image 'R2023-01-0506_39_05_1.25233.jpg' copied successfully.
Image 'R2023-01-0506_44_08_1.04167.jpg' copied successfully.
Image 'R2023-01-0506_44_08_1.04167.jpg' copied successfully.
Image 'R2023-01-0506_49_11_1.40833.jpg' copied successfully.
Image 'R2023-01-0506_49_11_1.40833.jpg' copied successfully.
Image 'R2023-01-0506_54_

Image 'R2023-01-0512_12_14_2.0.jpg' copied successfully.
Image 'R2023-01-0512_12_14_2.0.jpg' copied successfully.
Image 'R2023-01-0512_17_17_2.0.jpg' copied successfully.
Image 'R2023-01-0512_17_17_2.0.jpg' copied successfully.
Image 'R2023-01-0512_22_20_1.99967.jpg' copied successfully.
Image 'R2023-01-0512_22_20_1.99967.jpg' copied successfully.
Image 'R2023-01-0512_27_22_2.0.jpg' copied successfully.
Image 'R2023-01-0512_27_22_2.0.jpg' copied successfully.
Image 'R2023-01-0512_32_26_2.0.jpg' copied successfully.
Image 'R2023-01-0512_32_26_2.0.jpg' copied successfully.
Image 'R2023-01-0512_37_29_2.0.jpg' copied successfully.
Image 'R2023-01-0512_37_29_2.0.jpg' copied successfully.
Image 'R2023-01-0512_42_31_2.0.jpg' copied successfully.
Image 'R2023-01-0512_42_31_2.0.jpg' copied successfully.
Image 'R2023-01-0512_47_34_2.0.jpg' copied successfully.
Image 'R2023-01-0512_47_34_2.0.jpg' copied successfully.
Image 'R2023-01-0512_52_37_2.0.jpg' copied successfully.
Image 'R2023-01-0512_52

Image 'R2023-01-0518_15_40_1.36467.jpg' copied successfully.
Image 'R2023-01-0518_15_40_1.36467.jpg' copied successfully.
Image 'R2023-01-0518_20_43_1.301.jpg' copied successfully.
Image 'R2023-01-0518_20_43_1.301.jpg' copied successfully.
Image 'R2023-01-0518_25_46_1.27138.jpg' copied successfully.
Image 'R2023-01-0518_25_46_1.27138.jpg' copied successfully.
Image 'R2023-01-0518_30_49_1.14733.jpg' copied successfully.
Image 'R2023-01-0518_30_49_1.14733.jpg' copied successfully.
Image 'R2023-01-0518_35_52_1.18133.jpg' copied successfully.
Image 'R2023-01-0518_35_52_1.18133.jpg' copied successfully.
Image 'R2023-01-0518_40_55_1.23367.jpg' copied successfully.
Image 'R2023-01-0518_40_55_1.23367.jpg' copied successfully.
Image 'R2023-01-0518_45_58_1.21667.jpg' copied successfully.
Image 'R2023-01-0518_45_58_1.21667.jpg' copied successfully.
Image 'R2023-01-0518_51_00_1.14233.jpg' copied successfully.
Image 'R2023-01-0518_51_00_1.14233.jpg' copied successfully.
Image 'R2023-01-0518_56_03_1

Image 'R2023-01-0600_24_13_0.520667.jpg' copied successfully.
Image 'R2023-01-0600_24_13_0.520667.jpg' copied successfully.
Image 'R2023-01-0600_29_16_0.489333.jpg' copied successfully.
Image 'R2023-01-0600_29_16_0.489333.jpg' copied successfully.
Image 'R2023-01-0600_34_19_0.217333.jpg' copied successfully.
Image 'R2023-01-0600_34_19_0.217333.jpg' copied successfully.
Image 'R2023-01-0600_39_21_0.0613793.jpg' copied successfully.
Image 'R2023-01-0600_39_21_0.0613793.jpg' copied successfully.
Image 'R2023-01-0600_44_24_0.0523333.jpg' copied successfully.
Image 'R2023-01-0600_44_24_0.0523333.jpg' copied successfully.
Image 'R2023-01-0600_49_27_0.05.jpg' copied successfully.
Image 'R2023-01-0600_49_27_0.05.jpg' copied successfully.
Image 'R2023-01-0600_54_30_0.052.jpg' copied successfully.
Image 'R2023-01-0600_54_30_0.052.jpg' copied successfully.
Image 'R2023-01-0600_59_33_0.052.jpg' copied successfully.
Image 'R2023-01-0600_59_33_0.052.jpg' copied successfully.
Image 'R2023-01-0601_04_

Image 'R2023-01-0606_27_38_0.567241.jpg' copied successfully.
Image 'R2023-01-0606_27_38_0.567241.jpg' copied successfully.
Image 'R2023-01-0606_32_41_0.474.jpg' copied successfully.
Image 'R2023-01-0606_32_41_0.474.jpg' copied successfully.
Image 'R2023-01-0606_37_43_0.425667.jpg' copied successfully.
Image 'R2023-01-0606_37_43_0.425667.jpg' copied successfully.
Image 'R2023-01-0606_42_46_0.625667.jpg' copied successfully.
Image 'R2023-01-0606_42_46_0.625667.jpg' copied successfully.
Image 'R2023-01-0606_47_49_0.746333.jpg' copied successfully.
Image 'R2023-01-0606_47_49_0.746333.jpg' copied successfully.
Image 'R2023-01-0606_52_52_0.658667.jpg' copied successfully.
Image 'R2023-01-0606_52_52_0.658667.jpg' copied successfully.
Image 'R2023-01-0606_57_55_0.637931.jpg' copied successfully.
Image 'R2023-01-0606_57_55_0.637931.jpg' copied successfully.
Image 'R2023-01-0607_02_58_0.726.jpg' copied successfully.
Image 'R2023-01-0607_02_58_0.726.jpg' copied successfully.
Image 'R2023-01-0607

Image 'R2023-01-0612_31_06_1.87467.jpg' copied successfully.
Image 'R2023-01-0612_31_06_1.87467.jpg' copied successfully.
Image 'R2023-01-0612_36_09_1.941.jpg' copied successfully.
Image 'R2023-01-0612_36_09_1.941.jpg' copied successfully.
Image 'R2023-01-0612_41_12_1.98586.jpg' copied successfully.
Image 'R2023-01-0612_41_12_1.98586.jpg' copied successfully.
Image 'R2023-01-0612_46_15_1.9971.jpg' copied successfully.
Image 'R2023-01-0612_46_15_1.9971.jpg' copied successfully.
Image 'R2023-01-0612_51_18_2.0.jpg' copied successfully.
Image 'R2023-01-0612_51_18_2.0.jpg' copied successfully.
Image 'R2023-01-0612_56_21_2.0.jpg' copied successfully.
Image 'R2023-01-0612_56_21_2.0.jpg' copied successfully.
Image 'R2023-01-0613_01_23_2.0.jpg' copied successfully.
Image 'R2023-01-0613_01_23_2.0.jpg' copied successfully.
Image 'R2023-01-0613_06_26_2.0.jpg' copied successfully.
Image 'R2023-01-0613_06_26_2.0.jpg' copied successfully.
Image 'R2023-01-0613_11_29_2.0.jpg' copied successfully.
Image

Image 'R2023-01-0618_34_36_0.759667.jpg' copied successfully.
Image 'R2023-01-0618_34_36_0.759667.jpg' copied successfully.
Image 'R2023-01-0618_39_39_0.82.jpg' copied successfully.
Image 'R2023-01-0618_39_39_0.82.jpg' copied successfully.
Image 'R2023-01-0618_44_42_1.04467.jpg' copied successfully.
Image 'R2023-01-0618_44_42_1.04467.jpg' copied successfully.
Image 'R2023-01-0618_49_45_1.065.jpg' copied successfully.
Image 'R2023-01-0618_49_45_1.065.jpg' copied successfully.
Image 'R2023-01-0618_54_48_0.888965.jpg' copied successfully.
Image 'R2023-01-0618_54_48_0.888965.jpg' copied successfully.
Image 'R2023-01-0618_59_50_0.888965.jpg' copied successfully.
Image 'R2023-01-0618_59_50_0.888965.jpg' copied successfully.
Image 'R2023-01-0619_04_53_0.838.jpg' copied successfully.
Image 'R2023-01-0619_04_53_0.838.jpg' copied successfully.
Image 'R2023-01-0619_09_56_0.869333.jpg' copied successfully.
Image 'R2023-01-0619_09_56_0.869333.jpg' copied successfully.
Image 'R2023-01-0619_14_59_0.8

Image 'R2023-01-0700_38_02_0.49.jpg' copied successfully.
Image 'R2023-01-0700_38_02_0.49.jpg' copied successfully.
Image 'R2023-01-0700_43_05_0.458.jpg' copied successfully.
Image 'R2023-01-0700_43_05_0.458.jpg' copied successfully.
Image 'R2023-01-0700_48_08_0.268.jpg' copied successfully.
Image 'R2023-01-0700_48_08_0.268.jpg' copied successfully.
Image 'R2023-01-0700_53_10_0.0613333.jpg' copied successfully.
Image 'R2023-01-0700_53_10_0.0613333.jpg' copied successfully.
Image 'R2023-01-0700_58_13_0.0613333.jpg' copied successfully.
Image 'R2023-01-0700_58_13_0.0613333.jpg' copied successfully.
Image 'R2023-01-0701_03_16_0.0503448.jpg' copied successfully.
Image 'R2023-01-0701_03_16_0.0503448.jpg' copied successfully.
Image 'R2023-01-0701_08_19_0.04.jpg' copied successfully.
Image 'R2023-01-0701_08_19_0.04.jpg' copied successfully.
Image 'R2023-01-0701_13_22_0.03.jpg' copied successfully.
Image 'R2023-01-0701_13_22_0.03.jpg' copied successfully.
Image 'R2023-01-0701_18_25_0.0316667.j

Image 'R2023-01-0706_41_32_0.0673333.jpg' copied successfully.
Image 'R2023-01-0706_41_32_0.0673333.jpg' copied successfully.
Image 'R2023-01-0706_46_35_0.069.jpg' copied successfully.
Image 'R2023-01-0706_46_35_0.069.jpg' copied successfully.
Image 'R2023-01-0706_51_37_0.0693103.jpg' copied successfully.
Image 'R2023-01-0706_51_37_0.0693103.jpg' copied successfully.
Image 'R2023-01-0706_56_40_0.0713333.jpg' copied successfully.
Image 'R2023-01-0706_56_40_0.0713333.jpg' copied successfully.
Image 'R2023-01-0707_01_43_0.0733333.jpg' copied successfully.
Image 'R2023-01-0707_01_43_0.0733333.jpg' copied successfully.
Image 'R2023-01-0707_06_46_0.0703333.jpg' copied successfully.
Image 'R2023-01-0707_06_46_0.0703333.jpg' copied successfully.
Image 'R2023-01-0707_11_49_0.069.jpg' copied successfully.
Image 'R2023-01-0707_11_49_0.069.jpg' copied successfully.
Image 'R2023-01-0707_16_52_0.0686667.jpg' copied successfully.
Image 'R2023-01-0707_16_52_0.0686667.jpg' copied successfully.
Image 'R

# Define image size

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [ ]:
def image_size_normalize(train_data_dir,test_data_dir):
    # Define the image size and batch size
    image_size = (128, 128)
    batch_size = 32

    # Use data augmentation and normalization for the training set
    train_data_generator = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True
    )

    # Only normalize the testing set
    test_data_generator = ImageDataGenerator(rescale=1./255)

    # Load and preprocess the training data
    train_generator = train_data_generator.flow_from_directory(
        train_data_dir,
        target_size=image_size,
        batch_size=batch_size,
        class_mode='binary'
    )

    # Load and preprocess the testing data
    test_generator = test_data_generator.flow_from_directory(
        test_data_dir,
        target_size=image_size,
        batch_size=batch_size,
        class_mode='binary'
    )
        # Build the CNN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    # Compile the model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    # Train the model
    model.fit(
        train_generator,
        steps_per_epoch=train_generator.samples // batch_size,
        epochs=10,
        validation_data=test_generator,
        validation_steps=test_generator.samples // batch_size
    )

    model.save("D:\\FOG\\new_dataset\\training\\binary\\my_cnn_model.h5")

In [ ]:
# Define the paths to the train and test directories
train_data_dir = 'D:\\FOG\\new_dataset\\training\\binary'
test_data_dir = 'D:\\FOG\\new_dataset\\testing\\binary'
image_size_normalize(train_data_dir,test_data_dir)

Found 7353 images belonging to 2 classes.
Found 1081 images belonging to 2 classes.
Epoch 1/10
229/229 [==============================] - 97s 418ms/step - loss: 0.3454 - accuracy: 0.8435 - val_loss: 0.1510 - val_accuracy: 0.9555
Epoch 2/10
229/229 [==============================] - 95s 413ms/step - loss: 0.2142 - accuracy: 0.9124 - val_loss: 0.1874 - val_accuracy: 0.9223
Epoch 3/10
229/229 [==============================] - 97s 424ms/step - loss: 0.1905 - accuracy: 0.9276 - val_loss: 0.1192 - val_accuracy: 0.9498
Epoch 4/10
229/229 [==============================] - 94s 412ms/step - loss: 0.1675 - accuracy: 0.9340 - val_loss: 0.2233 - val_accuracy: 0.9413
Epoch 5/10
229/229 [==============================] - 94s 408ms/step - loss: 0.1683 - accuracy: 0.9348 - val_loss: 0.0910 - val_accuracy: 0.9574
Epoch 6/10
229/229 [==============================] - 95s 417ms/step - loss: 0.1468 - accuracy: 0.9460 - val_loss: 0.0966 - val_accuracy: 0.9489
Epoch 7/10
229/229 [==========================

# test accuracy

In [ ]:
# Evaluate the model on the testing set
test_loss, test_accuracy = model.evaluate(test_generator)
print(f'Test loss: {test_loss}')
print(f'Test accuracy: {test_accuracy}')

34/34 [==============================] - 4s 130ms/step - loss: 0.1225 - accuracy: 0.9556
Test loss: 0.12250979989767075
Test accuracy: 0.9555966854095459


In [ ]:
# name of classes
class_indices = train_generator.class_indices
class_names = list(class_indices.keys())
print("Class names:", class_names)

Class names: ['No_fog', 'fog']


In [ ]:
#prediction Report
# Generate predictions for the testing set
y_true = test_generator.classes
y_pred = model.predict(test_generator)
y_pred = y_pred.argmax(axis=1)

# Calculate precision, recall, and F1 score
report = classification_report(y_true, y_pred, target_names=test_generator.class_indices)
print(report)

34/34 [==============================] - 4s 128ms/step
              precision    recall  f1-score   support

      No_fog       0.32      1.00      0.48       345
         fog       0.00      0.00      0.00       736

    accuracy                           0.32      1081
   macro avg       0.16      0.50      0.24      1081
weighted avg       0.10      0.32      0.15      1081



C:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
def get_model_summary(model):
    stream = io.StringIO()
    model.summary(print_fn=lambda x: stream.write(x + '\n'))
    summary_string = stream.getvalue()
    stream.close()
    return summary_string

model_summary_string = model_summary(loaded_model)

print(model_summary_string)

# Validation

In [ ]:
import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow import keras
from PIL import Image

In [ ]:
train_data_dir = 'D:\\FOG\\new_dataset\\training\\binary'
test_data_dir = 'D:\\FOG\\new_dataset\\testing\\binary'

# Define the image size and batch size
image_size = (128, 128)
batch_size = 32

# Use data augmentation and normalization for the training set
train_data_generator = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

# Only normalize the testing set
test_data_generator = ImageDataGenerator(rescale=1./255)

# Load and preprocess the training data
train_generator = train_data_generator.flow_from_directory(
    train_data_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='binary'
)

# Load and preprocess the testing data
test_generator = test_data_generator.flow_from_directory(
    test_data_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='binary'
)

Found 7353 images belonging to 2 classes.
Found 1081 images belonging to 2 classes.


In [ ]:
# Load the saved model
loaded_model = load_model("D:\\FOG\\new_dataset\\training\\binary\\my_cnn_model.h5")

In [ ]:
# Load Validation Set

In [ ]:
folder_path = "D:\\FOG\\new_dataset\\validation\\binary\\fog\\"

In [ ]:
class_indices = train_generator.class_indices
print(class_indices)
class_labels = list(class_indices.keys())
print(class_labels)

{'No_fog': 0, 'fog': 1}
['No_fog', 'fog']


In [ ]:
# Get the list of all files in the folder
file_list = os.listdir(folder_path)

# Filter the list to only include image files (JPEG, PNG, and GIF)
image_list = [f for f in file_list if f.endswith('.jpg')]
print(len(image_list))
total_loss = 0
correct_predictions = 0
total_predictions = 0
miss_classified=[]
ground_truth_label = 'fog'  # Replace with the actual ground truth label
all_predictions= []

805


In [ ]:
ground_truth_index = class_labels.index(ground_truth_label)
print(ground_truth_index)

1


In [ ]:
import tensorflow as tf
import numpy as np
from PIL import Image


# Define the image preprocessing function
def preprocess_image(image_path):
    image = Image.open(image_path)
    image = image.resize((128, 128))  # Resize the image to match the input shape of the model
    image = np.array(image)  # Convert the image to a NumPy array
    image = image / 255.0  # Normalize the pixel values between 0 and 1
    return image


for all_images in image_list:
    all_images1 = str(folder_path) + str(all_images)
    # Preprocess and predict on an individual image
    # test_image_path = 'path_to_your_test_image.jpg'
    preprocessed_image = preprocess_image(all_images1)
    preprocessed_image = np.expand_dims(preprocessed_image, axis=0)  # Add an extra dimension to represent the batch size

    # Make predictions on the image
    predictions = loaded_model.predict(preprocessed_image)
    print("predictions  ", round(float(predictions),4))
    all_predictions.append(round(float(predictions),4))

    # Get the predicted class label
    predicted_class = 'fog' if predictions[0] > 0.5 else 'No_fog'

    print('Predicted class:', predicted_class)
    predicted_class_label= predicted_class

    ground_truth = tf.one_hot(ground_truth_index, len(class_labels))[tf.newaxis, :]
    print("ground_truth ",ground_truth)
    loss_value = tf.keras.losses.binary_crossentropy(ground_truth, predictions).numpy()

       # Calculate accuracy
    total_loss += loss_value
    total_predictions += 1

    if ground_truth_label == predicted_class_label:
        correct_predictions += 1
    else:
        miss_classified.append(all_images)
        print(len(miss_classified))

# Calculate average loss and accuracy
average_loss = total_loss / total_predictions
accuracy = correct_predictions / total_predictions

print("Average loss:", average_loss)
print("Accuracy:", accuracy)

1/1 [==============================] - 0s 63ms/step
predictions   0.2666
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1
1/1 [==============================] - 0s 16ms/step
predictions   0.6701
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.8008
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.8791
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.634
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9615
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/s

1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9995
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 20ms/step
predictions   0.002
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
2
1/1 [==============================] - 0s 18ms/s

1/1 [==============================] - 0s 16ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 7ms/step
p

1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 16ms/step
predictions   0.1376
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
19
1/1 [==============================] - 0s 22ms/step
predictions   0.076
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
20
1/1 [==============================] - 0s 31ms/step
predictions   0.069
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
21
1/1 [==============================] - 0s 24ms/step
predictions   0.0272
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
22
1/1 [==============================] - 0s 16ms/step
predictions   0.0407
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
23
1/1 [==============================] - 0s 16ms/step
predictions   0.0292
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
24
1/1 [=============

1/1 [==============================] - 0s 12ms/step
predictions   0.9619
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.7312
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9558
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9925
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9955
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9954
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 16ms/step
predictions   1.0
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 34ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
pre

1/1 [==============================] - 0s 31ms/step
predictions   0.965
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.4348
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
82
1/1 [==============================] - 0s 16ms/step
predictions   0.4896
Predicted class: No_fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
83
1/1 [==============================] - 0s 31ms/step
predictions   0.9628
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9528
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9393
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s

1/1 [==============================] - 0s 22ms/step
predictions   0.9995
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 22ms/step
predictions   0.9175
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.932
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.8354
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9503
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.8264
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9236
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 19ms/step
p

1/1 [==============================] - 0s 21ms/step
predictions   0.9742
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9566
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9859
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9912
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9657
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.969
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
p

1/1 [==============================] - 0s 16ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 33ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 35ms/step
predictions   0.9994
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 31ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9989
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9254
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9954
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
p

1/1 [==============================] - 0s 16ms/step
predictions   0.9991
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9995
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9986
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9994
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9981
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9973
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step


1/1 [==============================] - 0s 16ms/step
predictions   0.999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9991
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9993
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9996
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
p

1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 16ms/step
predictions   0.9997
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9998
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 31ms/step
predictions   0.9999
Predicted class: fog
ground_truth  tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
1/1 [==============================] - 0s 22ms/step


In [ ]:
from PIL import Image

# Define the image preprocessing function
def preprocess_image(image_path):
    image = Image.open(image_path)
    image = image.resize((720, 480))  # Resize the image to match the input shape of the model
    return image


print(len(miss_classified))
for all_images in miss_classified:

    all_images1 = str(folder_path) + str(all_images)
    preprocessed_image = preprocess_image(all_images1)
    preprocessed_image.save("D:\\FOG\\new_dataset\\misclassified\\binary\\No_fog\\" + all_images + ".jpg")


102


In [ ]:
import matplotlib.pyplot as plt

j=[]
for i in all_predictions:
    if i<0.5:
        i=0
    else:
        i=1
    j.append(i)

In [ ]:
plt.plot(all_predictions)

In [ ]:
plt.plot(j)